### ISSUE TITLE
Error import pynagios

### ISSUE THREAD

**Issue by DRAKUN** [kiip/pynagios#15]
>>> import pynagios
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pynagios
  File "C:\Users\Drak\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynagios\__init__.py", line 9, in <module>
    from plugin import Plugin, OK, WARNING, CRITICAL, UNKNOWN
ModuleNotFoundError: No module named 'plugin'
>>>

**Comment by mcm** [comment]
@DRAKUN I don't think pynagios has Python3 support. You can try our fork, pycinga, which works with Nagios as well. https://github.com/HurricaneLabs/python-pycinga
